### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by alyssais** [Homebrew/homebrew-portable#6]
Trying to build the docker image fails because it tries to run Linuxbrew as root, which Linuxbrew no longer allows.

**Comment by MikeMcQuaid** [comment]
I think it's probably worth removing all the Linux and non-Ruby stuff from this repo as they aren't maintained.

**Comment by alyssais** [comment]
Ah, that's a shame. I have a real need for something like this on Linux, so I'm going to spend some time trying to get it working. Are you interested in a PR for that, or will I just keep it on my fork?

**Comment by MikeMcQuaid** [comment]
For which packages?

**Comment by alyssais** [comment]
Whichever are necessary to get Ruby building.

So, currently I'm working on readline, which is broken.

**Comment by MikeMcQuaid** [comment]
yeh, would accept PR to get Ruby working 👍

**Comment by DoomHammer** [comment]
@sjackman this seems like a job for us, doesn't it?

**Comment by sjackman** [comment]
> @sjackman this seems like a job for us, doesn't it?

If you're volunteering, then yes. =)
A portable Ruby is quite useful for bootstrapping Linuxbrew. There's also [Traveling Ruby](http://phusion.github.io/traveling-ruby/).
